### PR TITLE
docs(economy): update fish hunt mine

### PR DESCRIPTION
**Pull request by konal1019**

### CODE REVIEW

**Review by mxz7 — CHANGES_REQUESTED** [review]
change the page title to fish hunt mine and its perfect

**Comment by aqua-flare** [comment]
> change the page title to fish hunt mine and its perfect

with or without spaces?

**Comment by mxz7** [comment]
@konal1019 i mean the page title, not the file name. the file name doesnt have too much importance as the user doesnt see it.

the page title is at the top of the file prefixed with #

**Comment by mxz7** [comment]
you must also update the SUMMARY.md file to reflect the file name change

**Comment by aqua-flare** [comment]
> you must also update the SUMMARY.md file to reflect the file name change

where do I find that

**Comment by mxz7** [comment]
> > you must also update the SUMMARY.md file to reflect the file name change
> 
> where do I find that

in the repo, did you even look?

**Pull request merged**
